
name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: [self-hosted, Windows, X64]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2.18
    - uses: seanmiddleditch/gha-setup-ninja@v4
    - uses: ilammy/msvc-dev-cmd@v1
      if: runner.os == 'Windows'
    - name: Generating Makefiles
      shell: bash
      run: |
        export enable_ccache=off
        curl -L https://github.com/blueloveTH/aseprite/releases/download/v0.01/libcrypto-1_1-x64.dll --output libcrypto-1_1-x64.dll
        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DLAF_BACKEND=skia \
          -DSKIA_DIR=C:/skia \
          -DSKIA_LIBRARY_DIR=C:/skia/out/Release-x64 \
          -DSKIA_LIBRARY=C:/skia/out/Release-x64/skia.lib \
    - name: Compiling
      shell: pwsh
      run: ninja -C build
    - uses: actions/upload-artifact@v4.6.2
      with:
        name: aseprite
        path: |
          libcrypto-1_1-x64.dll
          D:/a/aseprite/aseprite/build/bin/data
          D:/a/aseprite/aseprite/build/bin/aseprite.exe
